# config.yaml
#
#   This file defines the parameters for various aspects of the program.

datasets:
  src: datasets/CVD_unprocessed.csv   # The CSV that needs to be preprocessed.
  dest: datasets/CVD_processed.csv    # The location the final preprocessed CSV will go.
model_1:
  model: 1                            # Model number for graph filename
  momentum: 0.03                      #
  learning_rate: 0.01                 #
  epochs: 20                          #
  hidden_size: 21                     #
  test_size: 0.4                      #
  seed: 42                            #
model_2:
  model: 2                            # Model number for graph filename
  momentum: 0.03                      #
  learning_rate: 0.01                 #
  epochs: 20                          #
  hidden_size: 21                     #
  test_size: 0.4                      #
  seed: 42                            #